title: Jarno Tuovinen - Get Things Done
description: >
  Jarno Tuovinen is a seasoned DevOps engineer with over a decade of experience on wide variety of things. Main keywords are DevOps, AWS, Azure, Jenkins, CI/CD, Java (Android, Spring, Boot), Python, scripting and automation.
baseurl: ""
url: "http://jarnotuovinen.com"

markdown: kramdown
gems:
  - jekyll-sitemap

snapchat_username: mrtuovinen
twitter_username: mrtuovinen
linkedin_username: jarnotuovinen
github_username: spedepekka
youtube_username: JarnoTuovinenJT
